sudo: required
services:
  - docker

before_install:
  - docker build -t pecheriahadm/react-fibo -f ./client/Dockerfile.dev client

script:
  - docker run pecheriahadm/react-fibo npm run build

after_success:
  - docker build -t pecheriahadm/multi-client ./client
  - docker build -t pecheriahadm/multi-nginx ./nginx
  - docker build -t pecheriahadm/multi-server ./server
  - docker build -t pecheriahadm/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_NAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push pecheriahadm/multi-client
  - docker push pecheriahadm/multi-nginx
  - docker push pecheriahadm/multi-server
  - docker push pecheriahadm/multi-worker